language: ruby
rvm:
- 2.2.6
- 2.3.3
- 2.4.1
env:
  global:
  - secure: qXpWydxv6DHMrvGL8WH4wNRY4MTY7KV/x308Y5dHkZCrI7k9UOccvznp69KT3Z+tzYEFDXfUix5wA6pgyVcvrsQyiLSjGcyzHhxJKs1gk0gcxAkmhwHmUP9aiXWUe/mzpj7Uoc2DHwpPTpK1wQ5kV6eV+jzQLuN3nhfNr2sL8b4=
addons:
  code_climate:
    repo_token: TODO! UPDATE_THIS!
script: bundle exec rake test
after_success:
  - bundle exec codeclimate-test-reporter

